CREATE TABLE IF NOT EXISTS owner
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS movies
(
    id SERIAL PRIMARY KEY NOT NULL,
    owner_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    seen BOOLEAN NOT NULL,

    CONSTRAINT fk_movie_owner_id FOREIGN KEY (owner_id) REFERENCES movie(id)
);