# List of Movies
GET http://localhost:8080/movies HTTP/1.1
content-type: application/json

###

# Create new movie
POST http://localhost:8080/movies HTTP/1.1
content-type: application/json

{
    "id": 0,
    "owner_id": 1,
    "name": "Venom 3",
    "seen": false
}

###

# Update existing movie
PUT http://localhost:8080/movies/8 HTTP/1.1
content-type: application/json

{
    "owner_id": 8,
    "name": "Venom 3",
    "seen": true
}

###

# Update existing movie
DELETE http://localhost:8080/movies/1 HTTP/1.1
content-type: application/json